resources:
  - type: module
    url: /hacsfiles/simple-thermostat/simple-thermostat.js
  - type: module
    url: /hacsfiles/canvas-gauge-card/canvas-gauge-card.js
  - type: module
    url: /hacsfiles/weather-card/weather-card.js
  - type: module
    url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
  - type: module
    url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
  - type: module
    url: /hacsfiles/spotify-card/spotify-card.js


no-top-header:
  card-mod-theme: no-top-header
  card-mod-root: |
    app-toolbar {
      display: none;
    }

views:
  - title: Home
    background: var(--background-image)
    badges:
      - entity: binary_sensor.updater
      - entity: person.david_bryant
      - entity: person.wendy_bryant
      - entity: group.bryant_family
      - entity: sun.sun
      - entity: binary_sensor.ewelink_ms01_ecec6622_ias_zone

    cards:
      - type: glance
        title: Switches
        entities:
          - entity: switch.upstairs_light
            tap_action:
              action: light.toggle
          - entity: light.osram_classic_a60_w_clear_lightify_bdd2040a_level_on_off
            tap_action:
              action: toggle
          - entity: switch.spare_switch
            tap_action:
              action: toggle
          - entity: switch.samsung_q80_series_65
            tap_action:
              action: toggle


      - type: custom:spotify-card
      # account: <optional> which account to use for spotcast. Defaults to "default"
      # height: <optional pixels height for the playlist element. If content is larger scrolling will be enabled>
        limit: 5
      # device: <optional name of a device to pre-select>
      # playlist_type: <optional featured|discover-weekly> Change type of playlists shown. Default are your normal playlists.
      # always_play_random_song: <optional true> Set to start playlists from a random song.
      # country_code: <optional country code to show featured playlist relevent to a particular country. https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 >
      # hide_warning: <optional true> Hide warnings if they are displayed.
      # name: <optional name> Custom title. Leave empty to hide.
      # display_style: <optional Grid> Change default display style.
      # grid_covers_per_row: <optional number> Number of covers per row (default 3) in Grid-view.
      # spotify_entity: <optional> Name of your spotify media player entity if it doesn't start with "spotify"
        default_device: Yamaha Study Speaker
        filter_devices:
          - .*display
          - SHIELD*

      - type: entities
        entities:
          - sensor.auto_backup

      - type: horizontal-stack
        cards:
          - type: custom:canvas-gauge-card
            entity: sensor.cpu_temperature
            card_height: 62
            gauge:
              type: "radial-gauge"
              title: CPU Temperature
              width: 110
              height: 110
              borderShadowWidth: 0
              borderOuterWidth: 0
              borderMiddleWidth: 0
              borderInnerWidth: 0
              minValue: 0
              maxValue: 100
              startAngle: 90
              ticksAngle: 180
              valueBox: false
              majorTicks:
                ["0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"]
              minorTicks: 2
              strokeTicks: true
              highlights:
                [{ "from": 70, "to": 100, "color": "rgba(200, 50, 50, .75)" }]
              colorPlate: "#ddd"
              borders: false
              needleType: "arrow"
              needleWidth: 2
              needleCircleSize: 7
              needleCircleOuter: true
              needleCircleInner: false
              animationDuration: 1500
              animationRule: "linear"
          - type: custom:canvas-gauge-card
            entity: sensor.memory_use_percent
            card_height: 62
            gauge:
              type: "radial-gauge"
              title: Memory Usage (%)
              width: 110
              height: 110
              borderShadowWidth: 0
              borderOuterWidth: 0
              borderMiddleWidth: 0
              borderInnerWidth: 0
              minValue: 0
              maxValue: 100
              startAngle: 90
              ticksAngle: 180
              valueBox: false
              majorTicks:
                ["0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"]
              minorTicks: 2
              strokeTicks: true
              highlights:
                [{ "from": 80, "to": 100, "color": "rgba(200, 50, 50, .75)" }]
              colorPlate: "#ddd"
              borders: false
              needleType: "arrow"
              needleWidth: 2
              needleCircleSize: 7
              needleCircleOuter: true
              needleCircleInner: false
              animationDuration: 1500
              animationRule: "linear"
          - type: custom:canvas-gauge-card
            entity: sensor.processor_use
            card_height: 62
            gauge:
              type: "radial-gauge"
              title: Processor Usage (%)
              width: 110
              height: 110
              borderShadowWidth: 0
              borderOuterWidth: 0
              borderMiddleWidth: 0
              borderInnerWidth: 0
              minValue: 0
              maxValue: 100
              startAngle: 90
              ticksAngle: 180
              valueBox: false
              majorTicks:
                ["0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"]
              minorTicks: 2
              strokeTicks: true
              highlights:
                [{ "from": 80, "to": 100, "color": "rgba(200, 50, 50, .75)" }]
              colorPlate: "#ddd"
              borders: false
              needleType: "arrow"
              needleWidth: 2
              needleCircleSize: 7
              needleCircleOuter: true
              needleCircleInner: false
              animationDuration: 1500
              animationRule: "linear"

      - entity: climate.study
        sensors:
          - entity: sensor.study_humidity
            name: Humidity
        type: 'custom:simple-thermostat'
      - entity: climate.hollys_bedroom
        sensors:
          - entity: sensor.hollys_bedroom_humidity
            name: Humidity
        type: 'custom:simple-thermostat'
      - entity: climate.wendys_bedroom
        sensors:
          - entity: sensor.wendys_bedroom_humidity
            name: Humidity
        type: 'custom:simple-thermostat'
      - entity: climate.family_room
        sensors:
          - entity: sensor.family_room_humidity
            name: Humidity
        type: 'custom:simple-thermostat'
      - entities:
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
          - entity: sensor.speedtest_ping
        show_header_toggle: false
        title: Network
        type: entities
      - type: entities
        entities:
          - sensor.australia_coronavirus_confirmed
          - sensor.australia_coronavirus_current
          - sensor.australia_coronavirus_deaths
          - sensor.australia_coronavirus_recovered
        title: Corona Virus
      - type: entities
        entities:
          - sensor.act_garbage_last_updated
          - sensor.act_garbage_pickup
          - sensor.act_recycling_pickup
          - sensor.act_greenwaste_pickup
          - input_boolean.check_act_garbage
          - binary_sensor.act_garbage_today
          - binary_sensor.act_garbage_tomorrow
          - binary_sensor.act_recycling_today
          - binary_sensor.act_recycling_tomorrow
          - binary_sensor.act_greenwaste_today
          - binary_sensor.act_greenwaste_tomorrow
        title: ACT Garbage Collection
        show_header_toggle: false
  - title: Automations
    cards:
      - type: entities
        entities:
          - automation.turn_off_lights_at_a_time_if_home
          - automation.turn_off_stairs_lights_at_a_time_if_home
          - automation.turn_off_fam_lamp_at_a_time
          - automation.turn_on_lights_at_sundown_if_home
          - automation.turn_off_tv_at_a_time
          - automation.turn_off_ac_at_a_time
          - automation.wendy_ac_on_at_700pm_if_home
          - automation.test
      - type: entities
        entities:
          - script.study_speaker
          - script.study_speaker_off
          - automation.home_assistant_has_started
          - automation.study_ac_on_at_800am_if_home
          - automation.study_spotify_on_at_800am_if_home
          - automation.study_ac_after_800am_and_before_500pm_if_home
          - automation.study_ac_off_when_temp_20_225_or_1700_or_not_home
          - automation.study_spotify_off_when_1700_or_not_home
          - automation.holly_ac_on_at_500am_if_not_19_24_or_not_home
          - automation.holly_ac_off_when_temp_20_225_or_800am_or_930pm
          - automation.holly_ac_after_500am_and_before_800am_if_home
          - automation.holly_ac_on_at_830pm_if_not_19_24_or_home
          - automation.holly_ac_after_830pm_and_before_930pm_if_home
          - automation.notify_greenwaste_garbage_collection
          - automation.notify_recycling_garbage_collection


      - type: calendar
        title: 'Calendar'
        entities:
          - calendar.test_everything


      # - type: glance
      #   title: Switches
      #   entities:
      #     - entity: switch.frlawnwest
      #       tap_action:
      #         action: toggle
      #     - entity: switch.frlawneast
      #       tap_action:
      #         action: toggle
      #     - entity: switch.bklawnsouth
      #       tap_action:
      #         action: toggle
      #     - entity: switch.bklawnnorth
      #       tap_action:
      #         action: toggle
      #     - entity: switch.frontgarden
      #       tap_action:
      #         action: toggle
      #     - entity: switch.backsidegarden
      #       tap_action:
      #         action: toggle
      #     - entity: switch.tinybacklawn
      #       tap_action:
      #         action: toggle

            # - type: entities
      #   title: 'Garden Watering time'
      #   entities:
      #     - input_number.garden_watering_time
      # - type: entities
      #   title: 'smart_irrigation_base_schedule'
      #   entities:
      #     - sensor.smart_irrigation_base_schedule_index
      # - type: entities
      #   title: 'smart_irrigation_hourly_adjusted_run_time'
      #   entities:
      #     - sensor.smart_irrigation_hourly_adjusted_run_time
      # - type: entities
      #   title: 'sensor.smart_irrigation_daily_adjusted_run_time'
      #   entities:
      #     - sensor.smart_irrigation_daily_adjusted_run_time
      # - type: entities
      #   title: 'smart_irrigation_hourly_netto_precipitation'
      #   entities:
      #     - sensor.smart_irrigation_hourly_netto_precipitation
      # - type: entities
      #   title: 'smart_irrigation_bucket'
      #   entities:
      #     - sensor.smart_irrigation_bucket

  - title: Irrigation
    cards:
      - type: entities
        title: 'Irrigation Status'
        entities:
          - entity: switch.frlawnwest
            type: custom:multiple-entity-row
            name: frlawnwest
            toggle: true
            state_color: true
            entities:
              - entity: input_text.frlawnwest_run_time
                name: run time
              - entity: input_text.frlawnwest_run_date
                name: run date
              - entity: input_text.frlawnwest_run_duration
                name: run dur.
                format: duration
          - entity: switch.frlawneast
            type: custom:multiple-entity-row
            name: frlawneast
            toggle: true
            state_color: true
            entities:
              - entity: input_text.frlawneast_run_time
                name: false
              - entity: input_text.frlawneast_run_date
                name: false
              - entity: input_text.frlawneast_run_duration
                name: false
                format: duration
          - entity: switch.bklawnsouth
            type: custom:multiple-entity-row
            name: bklawnsouth
            toggle: true
            state_color: true
            entities:
              - entity: input_text.bklawnsouth_run_time
                name: false
              - entity: input_text.bklawnsouth_run_date
                name: false
              - entity: input_text.bklawnsouth_run_duration
                name: false
                format: duration
          - entity: switch.bklawnnorth
            type: custom:multiple-entity-row
            name: bklawnnorth
            toggle: true
            state_color: true
            entities:
              - entity: input_text.bklawnnorth_run_time
                name: false
              - entity: input_text.bklawnnorth_run_date
                name: false
              - entity: input_text.bklawnnorth_run_duration
                name: false
                format: duration
          - type: section
          - entity: switch.frontgarden
            type: custom:multiple-entity-row
            name: frontgarden
            toggle: true
            state_color: true
            entities:
              - entity: input_text.frontgarden_run_time
                name: false
              - entity: input_text.frontgarden_run_date
                name: false
              - entity: input_text.frontgarden_run_duration
                name: false
                format: duration
          - entity: switch.backsidegarden
            type: custom:multiple-entity-row
            name: backsidegarden
            toggle: true
            state_color: true
            entities:
              - entity: input_text.backsidegarden_run_time
                name: false
              - entity: input_text.backsidegarden_run_date
                name: false
              - entity: input_text.backsidegarden_run_duration
                name: false
                format: duration
          - entity: switch.tinybacklawn
            type: custom:multiple-entity-row
            name: tinybacklawn
            toggle: true
            state_color: true
            entities:
              - entity: input_text.tinybacklawn_run_time
                name: false
              - entity: input_text.tinybacklawn_run_date
                name: false
              - entity: input_text.tinybacklawn_run_duration
                name: false
                format: duration
          - type: section
          - entity: input_number.garden_watering_time
            type: custom:multiple-entity-row
            state_header: 'Garden'
            format: duration
            entities:
              - entity: sensor.smart_irrigation_hourly_adjusted_run_time
                attribute: adjusted_run_time_minutes
              - entity: sensor.smart_irrigation_daily_adjusted_run_time
                attribute: adjusted_run_time_minutes
          - entity: input_boolean.force_irrigation
            type: custom:multiple-entity-row
            name: Force irrigation
            state_header: 'Force'
            toggle: true
            format: duration
            entities:
              - attribute: base_schedule_index_minutes
                entity: sensor.smart_irrigation_base_schedule_index



      - type: entities
        title: 'Daily Forecast'
        entities:
          - sensor.wupws_temp
          - sensor.wupws_preciptotal
          - sensor.precip_chance
          - sensor.wupws_precip_chance_2d
          - sensor.wupws_windspeed
          - sensor.wupws_humidity
          - sensor.wupws_pressure
          - sensor.wupws_dewpt
          - sensor.wupws_solarradiation
          - sensor.high_temperature_today
          - sensor.low_temperature_today

      - type: custom:card-templater
        card:
          type: entities
          title: 'Weather Overview'
        entities:
          - entity: sensor.wupws_weather_1d
            state_template: >-
              {% if states('sensor.wupws_weather_1d') == 'unknown' %} . {% endif %}
          - sensor.wupws_weather_1n
          - sensor.wupws_weather_2d
          - sensor.wupws_weather_2n
          - sensor.wupws_weather_3d
          - sensor.wupws_weather_3n
          - sensor.wupws_weather_4d
          - sensor.wupws_weather_4n




  - title: Cameras
    cards:
      - type: picture-entity
        entity: camera.front_camera
        tap_action:
          action: call-service
          service: camera.snapshot
          service_data:
            entity_id: camera.front_camera
            filename: '/media/front_camera-{{ now().strftime("%Y-%m-%d-%H%M%S") }}.jpg'

      - type: picture-entity
        entity: camera.back_camera
        tap_action:
          action: call-service
          service: camera.snapshot
          service_data:
            entity_id: camera.back_camera
            filename: '/media/back_camera-{{ now().strftime("%Y-%m-%d-%H%M%S") }}.jpg'

    path: default_view
